language: generic
os: linux
dist: focal

cache:
  directories:
    - $HOME/.docker

before_install:
  - sudo apt-get update

script:
  - echo "$HARPOON_API_TOKEN" | docker login https://registry.harpooncorp.com -u montana --password-stdin
  - docker build --platform linux/amd64 -t harpoondemo .
  - docker tag harpoondemo:latest registry.harpooncorp.com/atest/harpoondemo:latest
  - docker push registry.harpooncorp.com/atest/harpoondemo:latest

branches:
  only:
    - master
